name: meter-reader
services:
  meter-reader-api:
    image: ${DOCKER_REGISTRY-}meter-reader-api
    build:
      context: .
      dockerfile: MeterReader/Dockerfile
    depends_on:
      postgresdb:
        condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgresdb;Database=${PSQL_DB};Username=${PSQL_USER};Password=${PSQL_PASS}

  postgresdb:
    image: postgres:17.4
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${PSQL_DB} -U ${PSQL_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: ${PSQL_DB}
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASS}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
